### PR TITLE
Fix loading fonts in web-worker

### LINKED ISSUE #602: Create @jimp/web-worker
# Expected Behavior

Jimp loaded in a webworker and easy to use

# Current Behavior

Jimp loads in browser and slow things down

### LINKED ISSUE #1286: Cannot load fonts in Web Worker
I am confused... was issue #289 ever considered? Using fonts in a WebWorker (still) does not work.
Example worker:
```
importScripts('./jimp.js');

(async () => {

  const font = await Jimp.loadFont('fonts/open-sans/open-sans-32-black/open-sans-32-black.fnt');

  self.addEventListener('message', e => {
    Jimp.read(e.data).then((img) => {
      img
      .print(font, 10, 10, "Hello World!")
      .getBase64(Jimp.AUTO, (err, src) => {
        if (err) throw err;
        self.postMessage(src);
      });
    });
  });

})();
```
The following error is thrown:
```
jimp.js:2 Uncaught (in promise) Error: error parsing font document is not defined
```
Using latest version of jimp (0.22.12)

_Originally posted by @av01d in https://github.com/jimp-dev/jimp/issues/289#issuecomment-2009614925_

### PR DESCRIPTION
**Pull request by hipstersmoothie**
closes #1286
closes #602 (by documenting how to use in worker)

### CODE REVIEW

File: plugins/plugin-print/src/load-bitmap-font.ts [hunk 1]
```diff
@@ -52,13 +56,70 @@ function parseFont(
...
-async function loadBitmapFontData(bufferOrUrl: string | Buffer) {
-  if (typeof bufferOrUrl === "string") {
+export async function loadBitmapFontData(
+  bufferOrUrl: string | Buffer
+): Promise<LoadedFont> {
+  const isWebWorker = self.document === undefined;
+
+  if (isWebWorker && typeof bufferOrUrl === "string") {
+    const res = await fetch(bufferOrUrl);
+    const text = await res.text();
```
Comment (hipstersmoothie) [inline plugins/plugin-print/src/load-bitmap-font.ts:89]: The library we use to parse font docs doesn't support workers. This should work in most ends

**Comment by hipstersmoothie** [comment]
:rocket: PR was released in [`v1.1.5`](https://github.com/jimp-dev/jimp/releases/tag/v1.1.5) :rocket:
